# Includes one of the default files in src/bootstrap/defaults
# profile = "library"
change-id = 118703

[llvm]
# Will download LLVM from CI if available on your platform.
download-ci-llvm = true

[build]
build = "x86_64-pc-windows-msvc"
target = [
    "i586-rust9x-windows-msvc",
    "i686-rust9x-windows-msvc",
    "x86_64-rust9x-windows-msvc",
    "x86_64-pc-windows-msvc",
]

docs = false

extended = true
tools = [
    #    "cargo",
    #    "clippy",
    "rustdoc",
    #    "rustfmt",
    #    "rust-analyzer",
    #    "analysis",
    "src",
    #    "rust-demangler",  # if profiler = true
]

[rust]
dist-src = true

[dist]
src-tarball = false

# for creating a downloadable package: python x.py install, then create an archive this
[install]
prefix = "../dist/rust9x"
sysconfdir = "."
