# This workflow will build the current toolchain automatically, and 
# push it into release.
# 
# It will also built-in an install script, which can scan it as a rustup toolchain, so
# that we can manage them easily.
#
# If we can, we will add multiple platform support (e.g. Windows, macOS, Linux)
# so that you can do cross-compile by using this toolchain.
# 
# Workflow file by "zhangxuan2011 <zx20110412@outlook.com>"

---

name: Build Rust9x Toolchain

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release, which must start with `v`"
        required: true
        default: "v1.93.0-rust9x"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows, x86_64
          - os: windows-latest
            arch: x64
            target: x86_64-pc-windows-msvc
            target_short: x86_64-windows
          
          # Windows, i686
          - os: windows-latest
            arch: x86
            target: i686-pc-windows-msvc
            target_short: i686-windows

          # Windows, i586
          - os: windows-latest
            arch: x86
            target: i586-pc-windows-msvc
            target_short: i586-windows

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up upstream
        run: git remote add upstream https://github.com/rust-lang/rust.git

      - name: Install NASM
        run: choco install nasm -y

      - name: Activate MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build toolchain
        env:
          # If this env exists, the commit hash is wrong and just return 404.
          GITHUB_ACTIONS: 
        run: |
          :: Avoid failed to unset
          set GITHUB_ACTIONS=

          :: Build & install in dist/rust9x
          python x.py install --config bootstrap.rust9x.toml --stage 2
          if %errorlevel% neq 0 exit /b 1

      - name: Pack toolchain
        run: |
          set VERSION=${{ github.ref_name }}
          set ARCHIVE_NAME=rust9x-toolchain-%VERSION%-${{ matrix.target_short }}.tar.gz

          :: Pack everything inside build
          tar -czvf "%ARCHIVE_NAME%" -C dist/rust9x .

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: rust9x-toolchain-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
